<h2 style="text-align: center;"><b>Python. Занятие 1: Основы</b></h2>

## Основы Python

### Структуры данных и встроенные функции

**Все типы данных** в Python относятся к одной из **2-х категорий**: **изменяемые (mutable)** и **неизменяемые (unmutable)**.   

*Неизменяемые объекты*:  
* числовые данные (int, float), 
* bool,
* None,
* символьные строки (class 'str'), 
* кортежи (tuple).  

*Изменяемые объекты*:  
* списки (list), 
* множества (set), 
* словари (dict).  

Вновь определяемые пользователем типы (классы) могут быть определены как неизменяемые или изменяемые. Изменяемость объектов определённого типа является принципиально важной характеристикой, определяющей, может ли объект такого типа **выступать в качестве ключа для словарей (dict)** или нет.

### tuple

In [ ]:
t = ('a', 5, 12.345)
t

('a', 5, 12.345)

In [ ]:
t.append(5)

AttributeError: ignored

In [ ]:
len(t)

3

#### Поменять переменные местами

In [ ]:
a = -5
b = 100

a, b = b, a

print('a:', a, '\nb:', b)

a: 100 
b: -5


### list

In [ ]:
a = list()
b = []

print(a == b)

True


In [ ]:
my_list = ['string', 100, 5.678, None]
my_list

['string', 100, 5.678, None]

In [ ]:
array = [37,34,26,85,67,96,53,42,45,65,74,78,]
array = list(array)
print(array, '|', type(array))

[37, 34, 26, 85, 67, 96, 53, 42, 45, 65, 74, 78] | <class 'list'>


In [ ]:
array[1]

In [ ]:
array[-1]

In [ ]:
for i in range(0, 5):
    print(i)

* Перевернуть список:

In [ ]:
array = array[::-1]
array

* Срезы (`slice`'s) - это объекты языка Python, позволяющие получить какую-то часть итерируемого объекта.  
Пример:

In [ ]:
foo = list(range(10))
foo

In [ ]:
foo[:5]

In [ ]:
foo[5:]

In [ ]:
foo[2:5]

* Списки можно "склеивать":

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)

### Задание 1

1. Даны два списка одинаковых размеров из одинаковых элементов:  
`items = [1 5 6 9 8 7 2 3 4]`  
`shuffled_items = [2 3 4 1 6 5 7 9 8]`  

2. Расставьте элементы (с помощью функции `sort()`) в списоке `items` так, чтобы получился список `shuffled_items`  

In [ ]:
items = [1, 5, 6, 9, 8, 7, 2, 3, 4]
shuffled_items = [2, 3, 4, 1, 6, 5, 7, 9, 8]
items.sort(key=lambda x: shuffled_items.index(x))
print(items)
print(shuffled_items)

---

### enumerate, zip

In [ ]:
first = 'a b c d e f g'.split(' ')
second = '1 2 3 4 '.split(' ')
print(first, second)
zip(first, second)

In [ ]:
first, second

In [ ]:
list(zip(first, second * 3, first, second * 2))

---

### Задание 2

1. Создайте список `a`, состоящий из каких-то элементов.
2. Создайте список `b` такого же размера, как `a`, состоящий из каких-то элементов.
3. Выведите нумерованный список пар из элементов списков `a` и `b`.

In [ ]:
a, b = ['a', 'b', 'c'], [1, 6, 9]
for i, pair in enumerate(zip(a, b)):
    print(f"IDX: {i}, PAIR: {pair}")

IDX: 0, PAIR: ('a', 1)
IDX: 1, PAIR: ('b', 6)
IDX: 2, PAIR: ('c', 9)


---

### Задание 3

*Выведите* список из 100 чисел *через запятую*. **Чистыми циклами пользоваться нельзя.** (list comprehensions можно)

In [ ]:
", ".join([str(i) for i in range(100)])

---

In [ ]:
l = ['agfkd.,f', 'Qksdf;sb&..', 'asdoo*', 'bgf...d', 're54()kj[]].']
for num, s in zip([x.count('.') for x in l], l):
    if num > 2:
        print(s)

In [ ]:
[s for num, s in zip([x.count('.') for x in l], l) if num > 2]

---

### modules

**Модули** - это "библиотеки" Python. То есть это самостоятельные, объединённые технически и логически, именованные части Python кода

* О модулях необходимо знать только одно - как их импортировать:

In [ ]:
import collections

* Импортировать только какой-то компонент из модуля:

In [ ]:
from collections import Counter

* Импортировать с другим именем (чаще всего используется для локаничности кода):

In [ ]:
import collections as cl

In [ ]:
count = cl.Counter()

Жизненный пример:

In [ ]:
import numpy as np

### files

In [ ]:
!echo 'test file for python-intro notebook' > test.txt

In [ ]:
path = './test.txt'

In [ ]:

file = open(path, mode='r')
print([line for line in file][0])
file.close()

| Режим | Обозначение |
|-------|-------------|
| **'r'**  | Открытие на **чтение** (является значением по умолчанию) |
| **'rb'** | Открытие на **чтение**, в предположении, что будут считываться **байты** |
| **'w'** | Открытие на **запись**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'wb**' | Открытие на **запись байтов**, содержимое файла удаляется. Если файла не существует, создается новый |
| **'a'** | Открытие на **дозапись**, информация добавляется **в конец файла** |
| **'r+'** | Открыть файл на **чтение И запись**. Если файла нет, **новый НЕ создаётся** |
| **'a+'** | Открыть файл на **чтение И запись в конец файла**. Если файла нет, **новый создаётся** |
| **'t'** | Открытие файла **как текстового** (по умолчанию) |

In [ ]:
with open(path, mode='r') as test_file:
    for line in test_file:
        print(line)



### exceptions

In [ ]:
dir(__builtin__)

In [ ]:
raise KeyboardInterrupt()

In [ ]:
my_dict = {1: 100, 2: 200}
print(my_dict['NEW'])

In [ ]:
try:
    my_dict = {1: 100, 2: 200}
    print(my_dict['NEW'])
except KeyError:
    print('Caught KeyError!')

### Полезные библиотеки Python

### glob

In [ ]:
import glob

In [ ]:
!ping google.com

In [ ]:
glob.glob('./[0-9].*')

In [ ]:
glob.glob('*.png')

In [ ]:
glob.glob('?.jpg')

In [ ]:
glob.glob('./**/', recursive=True)

In [ ]:
glob.glob('**/*.txt', recursive=True)

### tqdm

* Устанавливаем виджеты:

`pip install ipywidgets`  

(или `conda install -c conda-forge ipywidgets`)

* Разрешаем их использование в Jupyter Notebook:  

`jupyter nbextension enable --py --sys-prefix widgetsnbextension`  

* Перезагружаем ядро (Restart Kernel)  


* Устанавливаем tqdm:  

`pip install tqdm`  

(или `conda install -c conda-forge tqdm`)  

Больше про tqdm: https://pypi.python.org/pypi/tqdm

In [ ]:
from tqdm import tqdm
from tqdm import tnrange, tqdm_notebook
from time import sleep

In [ ]:
cnt = 0
for i in tqdm(range(1000)):
    sleep(0.01)
    cnt += 1

In [ ]:
for i in tnrange(10, desc='1st loop'):
    print(i)
    for j in tqdm_notebook(range(100), desc='2nd loop', leave=False):
        print(j)
        sleep(0.01)

### collections

* `defaultdict()` - класс словаря, у которого есть значение по умолчанию - порой очень пригождается:

In [ ]:
from collections import defaultdict

In [ ]:
d = defaultdict(int)

print(d.get('key', 0))

d['key'] = 5
print(d['key'])  # 5

In [ ]:
d = defaultdict(lambda: 'empty')
print(d['key'])

d['key'] = 'full'
print(d['key'])

In [ ]:
temp = defaultdict(lambda: 'empty')
temp['trata']
print(temp.keys(), temp['trata'])

In [ ]:
d = dict()
print(d)
if 'list1' in d.keys():
    d['list1'].append(100)
    d['list1'].append(200)
else:
    d['list1'] = []
print(d)
print(d['list1'])

* `Counter()` - класс словаря, предназначенного для счётчиков. По сути, `== defaultdict(int)`:

In [ ]:
from collections import Counter

In [ ]:
counter = Counter()

for word in dir(__builtin__):
    for letter in word:
        counter[letter] += 1  # или .update(value)
    
print(counter)

---

# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [ ]:
# !conda install numpy
# !pip3 install numpy

In [ ]:
import numpy as np

## 1. Одномерные массивы

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [ ]:
np.lookfor('mean value of array') 

***Далее можно почитать документацию про контретную функцию.***

In [ ]:
?np.ma.mean

In [ ]:
np.con*?

***Посмотрим на количественные характеристики ``ndarray``.***

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

In [ ]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

***Индексы.***

In [ ]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

***Последний элемент.***

In [ ]:
a[-1]

***Можем изменять объекты массива.***

In [ ]:
a[2] = -1
a

### **Задача 1:** 
Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер:

In [ ]:
# решение
a = np.array([1, 2, 3, 5])
print()

## Создание массивов.

In [ ]:
a = np.zeros(7) # массив из нулей
b = np.ones(7, dtype=np.int16) # массив из единиц
print(a)
print(b)

***Часто нужно создать нулевой массив такой же как другой.***

In [ ]:
c = np.zeros(7)
c

In [ ]:
c = np.zeros_like(b)
c

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [ ]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [ ]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

### **Задача 2:** 
создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [ ]:
import numpy as np

a = np.linspace(10, 32, 12)
print(a)
print('Шаг:', a[1]-a[0])

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
Шаг: 2.0


### ***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [ ]:
#решенение
a = np.logspace(1, 1000)
print(a)


[1.00000000e+001 2.44205309e+021 5.96362332e+041 1.45634848e+062
 3.55648031e+082 8.68511374e+102 2.12095089e+123 5.17947468e+143
 1.26485522e+164 3.08884360e+184 7.54312006e+204 1.84206997e+225
 4.49843267e+245 1.09854114e+266 2.68269580e+286 6.55128557e+306
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf]


/usr/local/lib/python3.7/dist-packages/numpy/core/function_base.py:265: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


## 2. Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [ ]:
print(a)
print(b)

In [ ]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

***Один из операндов может быть скаляром, а не массивом.***

In [ ]:
print(5*a)
print(10 + b)

In [ ]:
print((a + b) ** 2)
print(2 ** (a + b))

In [ ]:
np.cos(a)

In [ ]:
np.log(b)

***Логические операции также производятся поэлементно.***

In [ ]:
print(a > b)
print(a == b)
print(a >= 10)

In [ ]:
print(np.e, np.pi)

***Посмотрим на сортировку numpy-массивов.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

***Теперь попробуем как метод.***

In [ ]:
a.sort()
print(a)

In [ ]:
b = np.ones(5)
b

## Индексирование массивов и срезы

***Массив в обратном порядоке.***

In [ ]:
a[::-1]

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [ ]:
print(a)

In [ ]:
a[2:5]

In [ ]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

***Диапозоны с шагами.***

In [ ]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

### **Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице.

In [ ]:
# решение
import math
import numpy as np
a = np.linspace(-4*math.pi, 4*math.pi, 100)
print(a)
for i in range(100):
  a[i] = (math.sin(i)**2 + math.cos(i)**2) #да, я переписываю исходный массив
print(a)
np.all(a) == 1

[-12.56637061 -12.31250454 -12.05863847 -11.8047724  -11.55090632
 -11.29704025 -11.04317418 -10.7893081  -10.53544203 -10.28157596
 -10.02770988  -9.77384381  -9.51997774  -9.26611167  -9.01224559
  -8.75837952  -8.50451345  -8.25064737  -7.9967813   -7.74291523
  -7.48904915  -7.23518308  -6.98131701  -6.72745093  -6.47358486
  -6.21971879  -5.96585272  -5.71198664  -5.45812057  -5.2042545
  -4.95038842  -4.69652235  -4.44265628  -4.1887902   -3.93492413
  -3.68105806  -3.42719199  -3.17332591  -2.91945984  -2.66559377
  -2.41172769  -2.15786162  -1.90399555  -1.65012947  -1.3962634
  -1.14239733  -0.88853126  -0.63466518  -0.38079911  -0.12693304
   0.12693304   0.38079911   0.63466518   0.88853126   1.14239733
   1.3962634    1.65012947   1.90399555   2.15786162   2.41172769
   2.66559377   2.91945984   3.17332591   3.42719199   3.68105806
   3.93492413   4.1887902    4.44265628   4.69652235   4.95038842
   5.2042545    5.45812057   5.71198664   5.96585272   6.21971879
   6.4735848

True

## 3. Двумерные массивы

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

In [ ]:
a.ndim, a.shape, len(a), a.size

***Обращение по индексу.***

In [ ]:
a[1][1], a[1,1]

In [ ]:
a = np.ones((3, 3)) # подать tuple
print(a)

In [ ]:
b = np.zeros((3, 4))
print(b)

In [ ]:
c = np.eye(3)
print(c)

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

### ***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [ ]:
# решение
a = np.diag(np.array([i for i in range(3, 30, 3)]))
j = -1
for i in range(9):
  a[i, j] = 4 + j
  j += -1

print(a)
#если что, главная и побочная диагонали пересекаются и, естественно, элемент на их пересечении меняет своё значение.
# это если я правильно понял задание, что на побочной диагонали должна быть арифметическая прогрессия с шагом -1 (начиная с 3)

[[ 3  0  0  0  0  0  0  0  3]
 [ 0  6  0  0  0  0  0  2  0]
 [ 0  0  9  0  0  0  1  0  0]
 [ 0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0]
 [ 0  0  0 -2  0 18  0  0  0]
 [ 0  0 -3  0  0  0 21  0  0]
 [ 0 -4  0  0  0  0  0 24  0]
 [-5  0  0  0  0  0  0  0 27]]


***Умножение матриц.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [ ]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 
a =np.array([2,5,8])
b= np.array([5,3,7])
print(a.dot(b))

***Маски.***

In [ ]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

***След (trace) - сумма диагональных элементов.***

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

## 4. Тензоры (многомерные массивы)

In [ ]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

In [ ]:
X.shape, len(X), X.size, X.ndim

***Посмотрим на суммы по разным осям.***

In [ ]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

## 5. Линейная алгебра

In [ ]:
a = np.array([[2, 1], [2, 3]])
print(a)

***Определитель.***

In [ ]:
np.linalg.det(a)

***Нахождениия обратной.***

In [ ]:
b = np.linalg.inv(a)
print(b)

# Pandas

Библиотека `pandas` активно используется в современном data science для работы с данными, которые могут быть представлены в виде таблиц (а это очень, очень большая часть данных)

`pandas` есть в пакете Anaconda, но если вдруг у Вас её по каким-то причинам нет, то можно установить, раскомментировав одну из следующих команд:

In [ ]:
# !pip3 install pandas
# !conda install pandas

In [ ]:
import numpy as np
import pandas as pd # Стандартное сокращение для pandas. Всегда используйте его!

## pd.Series

Тип данных pd.Series представляет собой одномерный набор данных. Отсутствующий данные записываются как `np.nan` (в этот день термометр сломался или метеоролог был пьян); они не участвуют в вычислении средних, среднеквадратичных отклонений и т.д.

### Создание
Создадим Series из списка температур

In [ ]:
some_list = [1, 3, 5, np.nan, 6, 8]
ser_1 = pd.Series(some_list)
ser_1

In [ ]:
# Так же можно в явном виде указать индексы, чтобы потом было более удобно обращаться к элементам
ind = ['1st day', '2nd day', '3rd day', '4th day', '5rd day', '6th day']

ser_2 = pd.Series(some_list, index=ind)
ser_2

In [ ]:
ser_2['4th day']

In [ ]:
# А еще можно дать pd.Series имя, чтобы было совсем красиво
ser_3 = pd.Series(some_list, index=ind, name='Temperature')
ser_3

### Индексирование
С индексами можно работать так же, как и в случае с обычным list.

In [ ]:
print(ser_3[0])

print('-----------')

print(ser_3[1:3])

print('-----------')

print(ser_3[::-1])

### Индексирование pd.Series по условиям

In [ ]:
date_range = pd.date_range('20190101', periods=10)
ser_4 = pd.Series(np.random.rand(10), index=date_range)
ser_4

In [ ]:
ser_4 > 0.5

В качестве индекса можно указать выражение, и нам будут возвращены только те элементы, для которых значение является `True`

In [ ]:
ser_4[ser_4 > 0.5]

In [ ]:
ser_4[(ser_4 > 0.6) | (ser_4 < 0.2)]

In [ ]:
ser_4[(ser_4 > 0.6) & (ser_4 < 0.2)]

### Сортировки
Тип `pd.Series` можно отсортировать как по значениям, так и по индексу.

In [ ]:
ser_4.sort_index()

In [ ]:
ser_4 = ser_4.sort_values()

In [ ]:
ser_4

### Операции с series
Тип `pd.Series` можно модифицировать проще, чем стандартный ``list`` из Python.

In [ ]:
ser_4 + 100

In [ ]:
np.exp(ser_4)

In [ ]:
term_1 = pd.Series(np.random.randint(0, 10, 5))
term_2 = pd.Series(np.random.randint(0, 10, 6))

term_1 + term_2

In [ ]:
term_1.shape

# pd.DataFrame

Тип данных pd.DataFrame представляет собой двумерную таблицу с данными. Имеет индекс и набор столбцов (возможно, имеющих разные типы). Таблицу можно построить, например, из словаря, значениями в котором являются одномерные наборы данных.
### Создание и основные объекты

In [ ]:
# Dataframe можно составить из словаря. Ключ будет соответсовать колонке
some_dict = {'one': pd.Series([1,2,3], index=['a','b','c']),
             'two': pd.Series([1,2,3,4], index=['a','b','c','d']),
             'three': pd.Series([5,6,7,8], index=['a','b','c','d'])}
df = pd.DataFrame(some_dict)
df

In [ ]:
#Альтернативно, из списка списков с аргументом columns

some_array = [[1,1,5], [2,2,6], [3,3,7], [np.nan, 4,8]]
df = pd.DataFrame(some_array, index=['a', 'b', 'c', 'd'], columns=['one', 'two', 'three'])
df

In [ ]:
df.values

In [ ]:
df.columns

In [ ]:
df.columns = ['first_column', 'second_column', 'third_column']
df.index = [1,2,3,4]
df

### Индексирование 
Есть очень много способов индексировать DataFrame в Pandas. Не все из них хорошие! Вот несколько удобных, но не универсальных.

#### По колонкам
Индексирование по колонке возращает pd.Series. Можно выбирать не одну колонку, а сразу несколько. Тогда снова вернётся pd.DataFrame.

In [ ]:
first_column = df['first_column']
first_column

In [ ]:
df.first_column

In [ ]:
subset_dataframe = df[['first_column', 'second_column']]
subset_dataframe

In [ ]:
one_column_dataframe = df[['first_column']]
one_column_dataframe

#### По строкам
Можно писать любые слайсы, как в Python-списке. Они будут применяться к строкам. Нельзя обращаться по элементу!

In [ ]:
df[1] # не сработает

In [ ]:
df[:1]

In [ ]:
df[1:4]

#### Универсальное индексирование: .loc и .iloc

.loc и .iloc --- это два взаимозаменяемых атрибута, которые позволяют индексировать по обеим осям сразу. Путаницы не возникает из-за фиксированного порядка перечисления осей.

In [ ]:
# По индексам: 
df.iloc[1:3, :2]

In [ ]:
df.loc[1:3, ['first_column', 'second_column']]

Лучше использовать по умолчанию либо только loc, либо только .iloc! А лучше вообще всегда только .iloc, чтобы не запутаться.

### Модификации датасета, создание новых колонок
Можно просто брать и создавать новую колонку. Синтаксис тут вполне естественный.

In [ ]:
new_column = [5,2,1,4]
df['new_column'] = new_column
df

Аналогично, можно применять к отдельным колонкам арифметические операции (ведь колонки --- это Series!)

In [ ]:
df['first_column'] = df['first_column'] * 10
df

## Реальный датасет
Мы будем работать с датасетом ``Титаник``. Файлы необходимо скачать локально или загрузить с помощью функции ниже.
![alt text](https://drive.google.com/uc?id=1Tb52nFFsjI8sqv0AlMpx25aNJ62xzp5w)

Информация о файлах: 
 - *titanic_data.csv* содержит различную информацию о пассажирах Титаника (билет, класс, возраст и т.п.)
 - *titanic_surv.csv* содержит для каждого пассажира из первого файла информацию о том, выжил ли этот пассажир (метка 1) или нет (метка 0)


### Чтение из файла
Обычно данные хранятся в виде таблиц в файлах формата .csv или .xlsx. На этом семинаре мы будем загружать данные из .csv файлов.


 
Загрузим первый файл

In [ ]:
# df_1 = pd.read_csv('titanic_data.csv')
import pandas as pd
pass_link = 'https://www.dropbox.com/s/lyzcuxu1pdrw5qb/titanic_data.csv?dl=1'
titanic_passengers = pd.read_csv(pass_link, index_col='PassengerId') # index_col=?

In [ ]:
print('Всего пассажиров: ', len(titanic_passengers))
titanic_passengers.head(10)

Всего пассажиров:  891


Pclass  ... Embarked
PassengerId          ...         
1                 3  ...        S
2                 1  ...        C
3                 3  ...        S
4                 1  ...        S
5                 3  ...        S
6                 3  ...        Q
7                 1  ...        S
8                 3  ...        S
9                 3  ...        S
10                2  ...        C

[10 rows x 10 columns]

### Разная информация о датасете

Можно узнать размер таблицы, информацию о значениях таблицы, различные статистики по значениям.

In [ ]:
titanic_passengers.shape

In [ ]:
titanic_passengers.info()

In [ ]:
titanic_passengers.describe()

## Задание 1 
Опишите данный датасет: какое расределение женщин/мужчин в нем? Сколько пассажиров ехало в каждом классе? Какой средний/минимальный/максимальный возраст пассажиров?

In [ ]:
(titanic_passengers['Age'].min(), titanic_passengers['Age'].mean(), titanic_passengers['Age'].max())

(0.42, 29.69911764705882, 80.0)

In [ ]:
titanic_passengers['Sex'].value_counts()

In [ ]:
titanic_passengers['Pclass'].value_counts()

## Задание 2
Сгруппируйте записи по классам пассажиров, в каждой группе посчитайте средний возраст. Используйте метод ``pandas.DataFrame.groupby``.

In [ ]:
# решение
a = titanic_passengers.groupby(by = 'Pclass').mean()['Age']
print(a)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64


## Слияние таблиц
Таблицы можно сливать несколькими способами. Мы рассмотрим слияние по индексу: метод называется ``pd.join``.

In [ ]:
# df_2 = pd.read_csv('titanic_surv.csv')
surv_link = 'https://www.dropbox.com/s/v35x9i6a1tc7emm/titanic_surv.csv?dl=1'
df_2 = pd.read_csv(surv_link)

In [ ]:
df_2.head()

### Задание 3.
Слейте два датасета по колонке индекса.

In [50]:
# решение
import pandas as pd
pass_link = 'https://www.dropbox.com/s/lyzcuxu1pdrw5qb/titanic_data.csv?dl=1'
df_1 = pd.read_csv(pass_link)

surv_link = 'https://www.dropbox.com/s/v35x9i6a1tc7emm/titanic_surv.csv?dl=1'
df_2 = pd.read_csv(surv_link)

df_3 = df_1.join(df_2) 

### Задание 4. 
Сколько всего выживших пассажиров? Выживших пассажиров по каждому из полов? Постройте матрицу корреляций факта выживания, пола и возраста.

In [51]:
# решение

df_2.head()
a_sex = df_3.groupby(by = 'Sex')['Survived'].sum()
print(a_sex)
print()
kar = df_3[['Sex', 'Age', 'Survived']]
kar.loc[(kar['Sex'] == 'female'), 'Sex'] = 1
kar.loc[(kar['Sex'] == 'male'), 'Sex'] = 0
kar = kar.fillna(0)
print(kar)
print()
print('Матрица корреляций')
print(kar.corr)

Sex
female    233
male      109
Name: Survived, dtype: int64

     Sex   Age  Survived
0      0  22.0         0
1      1  38.0         1
2      1  26.0         1
3      1  35.0         1
4      0  35.0         0
..   ...   ...       ...
886    0  27.0         0
887    1  19.0         1
888    1   0.0         0
889    0  26.0         1
890    0  32.0         0

[891 rows x 3 columns]

Матрица корреляций
<bound method DataFrame.corr of      Sex   Age  Survived
0      0  22.0         0
1      1  38.0         1
2      1  26.0         1
3      1  35.0         1
4      0  35.0         0
..   ...   ...       ...
886    0  27.0         0
887    1  19.0         1
888    1   0.0         0
889    0  26.0         1
890    0  32.0         0

[891 rows x 3 columns]>


/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [ ]:
#import seaborn as sns - а мы пошли своим путём)

In [ ]:
'''
#sns.heatmap(
    # сюда нужно подставить матрицу корреляции
  #  annot=True, cmap='coolwarm',
    vmin=-1, vmax=1,
    annot_kws={"size": 16})
'''